[workspace]
resolver = "2"
members = [
    "crates/smog",
    "examples/*",
]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.84"
version = "0.1.0"

[workspace.dependencies]
smog = { version = "0.1.0", path = "crates/smog" }
