[workspace]
resolver = "2"
members = [
    "crates/gtor",
    "crates/gtor-macro",
    "examples/*",
]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.84"
version = "0.1.0"

[workspace.dependencies]
gtor = { version = "0.1.0", path = "crates/gtor" }
gtor-macro = { version = "0.1.0", path = "crates/gtor-macro" }
